name: masa3MC
version: 1.8.1-RBCustom
main: net.masa3mc.pvp2.Main
author: uz_masa3
commands:
   kitmenu:
      description: open kit menu.
      permission: masa3MC.command.kitmenu
   setkit:
      description: save kit.
      permission: masa3MC.command.setkit
   loadkit:
      description: load kit.
      permission: masa3MC.command.loadkit
   game:
      description: game command.
      permission: masa3MC.command.game
   point:
      description: show user point.
      permission: masa3MC.command.point
   setting:
      description: Setings
      permission: masa3MC.command.setting
permissions:
  masa3MC.command.kitmenu:
    default: true
  masa3MC.command.setkit:
    default: op
  masa3MC.command.loadkit:
    default: op
  masa3MC.command.game:
    default: op
  masa3MC.command.point:
    default: true
  masa3MC.command.setting:
    default: op


