name: masa3MC
version: 1.8.1-Dev
main: net.masa3mc.pvp2.Main
author: uz_masa3
commands:
   kit:
      description: kit command.
      permission: masa3MC.command.kit
   game:
      description: game command.
      permission: masa3MC.command.game
   point:
      description: show user point.
      permission: masa3MC.command.point
   setting:
      description: Setings
      permission: masa3MC.command.setting
permissions:
  masa3MC.command.kit:
    default: true
  masa3MC.command.point:
    default: true
  masa3MC.command.game:
    default: op
  masa3MC.command.setting:
    default: op


